<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Rubys-MacBook-Air.local" failures="3" tests="7" name="Default test" time="172.926" errors="0" timestamp="2024-11-12T09:52:06 PST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="18.608"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="16.203"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="26.132"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="28.248">
    <failure type="java.lang.AssertionError" message="Unexpected alert message: This user already exist.">
      <![CDATA[java.lang.AssertionError: Unexpected alert message: This user already exist.
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at stepdefinitions.loginstep.user_should_be_successfully_registered(loginstep.java:169)
at ✽.User should be successfully registered(file:///Users/rubyverma/eclipse-workspace/certificateProject_edu/src/test/resources/feautres/demoblaze.feature:38)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="27.658">
    <failure type="java.lang.AssertionError" message="Unexpected alert message: This user already exist.">
      <![CDATA[java.lang.AssertionError: Unexpected alert message: This user already exist.
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at stepdefinitions.loginstep.user_should_be_successfully_registered(loginstep.java:169)
at ✽.User should be successfully registered(file:///Users/rubyverma/eclipse-workspace/certificateProject_edu/src/test/resources/feautres/demoblaze.feature:38)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="27.638">
    <failure type="java.lang.AssertionError" message="Unexpected alert message: This user already exist.">
      <![CDATA[java.lang.AssertionError: Unexpected alert message: This user already exist.
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at stepdefinitions.loginstep.user_should_be_successfully_registered(loginstep.java:169)
at ✽.User should be successfully registered(file:///Users/rubyverma/eclipse-workspace/certificateProject_edu/src/test/resources/feautres/demoblaze.feature:38)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="28.157"/>
</testsuite> <!-- Default test -->
